### ISSUE TITLE
desurium won't compile with bison 2.6

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#275]
I constantly get an compiling error on gentoo with cef.
https://gist.github.com/3173663

it seems to be a namespace error because adding on line 480 :: before the functinon xpathyyparse in
Desurium/build/chromium-prefix/src/chromium/src/third_party/WebKit/Source/WebCore/xml/XPathParser.cpp
fixes it for me

**Comment by karolherbst** [comment]
the problem is, that the function from where the function is included is generated, so this change could break it for anyone else.

```
third_party/WebKit/Source/WebCore/xml/XPathParser.cpp:480:39: error: too many arguments to function 'int WebCore::XPath::xpathyyparse()'
In file included from third_party/WebKit/Source/WebCore/xml/XPathParser.cpp:51:0:
/var/tmp/portage/games-util/desurium-9999/work/desurium-9999_build/chromium-prefix/src/chromium/src/out/Release/obj/gen/webkit/XPathGrammar.hpp:108:5: note: declared here
```

I don't know where is generating this file, but it could be yasm, but I'm not sure with this.

**Comment by matthiaskrgr** [comment]
I get this issue as well.

**Comment by lodle** [comment]
Can you guys find what files that xpathyparse is defined in?

**Comment by matthiaskrgr** [comment]
with these changes http://pastebin.com/kEzmiHUs
I get this output: http://pastebin.com/qfCdiL9B

**Comment by r-ick** [comment]
https://code.google.com/p/chromium/issues/detail?id=138243
https://bugs.webkit.org/show_bug.cgi?id=92264

The WebKit patch fixes this for me.

**Comment by TheSiege** [comment]
bison 2.6 makes sense to cause the problem. install date is around the time the problems happened

**Comment by karolherbst** [comment]
okay, I will try to include the patch in our build process on Monady

**Comment by karolherbst** [comment]
commit will be ready later this day
