### ISSUE TITLE
cef compile error because of nss 3.15

### ISSUE THREAD

**Issue by TheSiege** [desura/Desurium#572]
http://bpaste.net/show/113645/

**Comment by karolherbst** [comment]
this is the important part:

```
net/base/x509_certificate_nss.cc: In function 'void net::{anonymous}::ParsePrincipal(CERTName*, net::CertPrincipal*)':
net/base/x509_certificate_nss.cc:322:46: error: invalid conversion from 'char* (*)(const CERTName*) {aka char* (*)(const CERTNameStr*)}' to 'CERTGetNameFunc {aka char* (*)(CERTNameStr*)}' [-fpermissive]
       CERT_GetStateName, CERT_GetCountryName };
                                              ^
net/base/x509_certificate_nss.cc:322:46: error: invalid conversion from 'char* (*)(const CERTName*) {aka char* (*)(const CERTNameStr*)}' to 'CERTGetNameFunc {aka char* (*)(CERTNameStr*)}' [-fpermissive]
net/base/x509_certificate_nss.cc:322:46: error: invalid conversion from 'char* (*)(const CERTName*) {aka char* (*)(const CERTNameStr*)}' to 'CERTGetNameFunc {aka char* (*)(CERTNameStr*)}' [-fpermissive]
net/base/x509_certificate_nss.cc:322:46: error: invalid conversion from 'char* (*)(const CERTName*) {aka char* (*)(const CERTNameStr*)}' to 'CERTGetNameFunc {aka char* (*)(CERTNameStr*)}' [-fpermissive]
```

**Comment by karolherbst** [comment]
okay this might be a nss problem

**Comment by karolherbst** [comment]
does it work with nss-3.14.3?

**Comment by TheSiege** [comment]
yes; it works with 3.14; so 3.15 causes the breakage
